[package]
name = "libpixels"
version = "0.2.0"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
pixels = "0.10"
raw-window-handle = "0.4"
imgref = "1.9"
euclid = "0.22"
log = "0.4"
env_logger = "0.9"
value-box = "1.1"
array-box = "1.0"

[lib]
name = "Pixels"
crate-type = ["cdylib"]