[package]
name = "libpixels"
version = "1.0.0"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
pixels = "0.11"
raw-window-handle = "0.5"
imgref = "1.9"
euclid = "0.22"
log = "0.4"
env_logger = "0.10"
array-box = "1.0"
value-box = "2.2"
value-box-ffi = { version = "1.0", features = [ "array-box"] }

[lib]
name = "Pixels"
crate-type = ["cdylib"]
