[package]
name = "libpixels"
version = "0.1.0"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
pixels = "0.9"
raw-window-handle = "0.4.2"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer", rev = "8ffd345b6aabda55c5ab1b4914f6f3e5f92918d4" }

[lib]
name = "Pixels"
crate-type = ["cdylib"]